using System.Collections.Concurrent;
using War3Net.Drawing.Blp;

namespace MangosSuperUI.Services;

/// <summary>
/// On-demand character model GLB generator.
///
/// Mirrors the pattern of <see cref="ItemTextureService.EnsureGlb"/>:
///   - Caller asks for race + gender → service returns a web-relative URL
///     to a GLB under /character_models/
///   - First request extracts the M2 + skin BLP from the MPQ, parses, and writes
///     the GLB and skin PNG to disk
///   - Subsequent requests hit the disk cache (no MPQ work)
///
/// The cache directory is excluded from rsync deploys so generated GLBs survive
/// service restarts (same convention as /icons, /item_models, /minimap, etc.).
///
/// Race/gender validation: only the 8 vanilla races × 2 genders are accepted.
/// Anything else returns null, so an arbitrary URL parameter can't trick the
/// service into trying to extract garbage from the MPQ.
/// </summary>
public class CharacterModelService
{
    private readonly MpqReaderService _mpq;
    private readonly IWebHostEnvironment _env;
    private readonly CharacterSkinCompositor _skinCompositor;
    private readonly DbcService _dbcResolver;
    private readonly ILogger<CharacterModelService> _logger;

    // Concurrent locks per (race+gender) — keeps two simultaneous requests from
    // double-generating the same file. Same trick as ItemTextureService.
    private readonly ConcurrentDictionary<string, SemaphoreSlim> _locks = new();

    public CharacterModelService(
        MpqReaderService mpq,
        IWebHostEnvironment env,
        CharacterSkinCompositor skinCompositor,
        DbcService dbcResolver,
        ILogger<CharacterModelService> logger)
    {
        _mpq = mpq;
        _env = env;
        _skinCompositor = skinCompositor;
        _dbcResolver = dbcResolver;
        _logger = logger;
    }

    private static readonly HashSet<string> ValidRaces = new(StringComparer.OrdinalIgnoreCase)
    {
        "Human", "Dwarf", "NightElf", "Gnome",
        "Orc", "Tauren", "Troll", "Scourge"
        // "Scourge" is the vanilla MPQ folder name for Undead.
    };

    private static readonly HashSet<string> ValidGenders = new(StringComparer.OrdinalIgnoreCase)
    {
        "Male", "Female"
    };

    private string CharacterModelsDir => Path.Combine(_env.WebRootPath, "character_models");
    private string CharacterSkinsDir => Path.Combine(_env.WebRootPath, "character_textures", "skin");

    /// <summary>
    /// Build the web URL for a (race, gender)'s default skin PNG. The
    /// PNG is generated by EnsureCharacterGlbAsync; this method just
    /// computes the URL that file will/does live at.
    ///
    /// Returns null for invalid race/gender. Returns the URL even if the
    /// file doesn't exist on disk yet — callers should pair this with
    /// EnsureCharacterGlbAsync (which generates both files) before
    /// expecting the URL to resolve.
    ///
    /// Used by ItemsController.CharacterPreview to publish data-skin-url
    /// on the canvas element, so equip.js's loadDefaultSkin doesn't have
    /// to know the file's versioning scheme.
    /// </summary>
    public string? GetSkinPngUrl(string race, string gender)
    {
        if (!ValidRaces.Contains(race) || !ValidGenders.Contains(gender))
            return null;
        race = NormalizeRace(race);
        gender = NormalizeGender(gender);
        string key = race + gender;
        var filename = CacheVersionRegistry.MakeVersioned(
            $"{key}Skin00_00.png", CacheVersionRegistry.SkinPngVersion);
        return $"/character_textures/skin/{filename}";
    }

    /// <summary>
    /// Ensures a character GLB exists for the given race/gender, generating it on demand.
    /// Returns a web-relative URL (e.g. "/character_models/HumanMale.glb"), or null if
    /// race/gender is invalid or the underlying MPQ asset can't be found.
    /// </summary>
    public async Task<string?> EnsureCharacterGlbAsync(string race, string gender)
    {
        if (!ValidRaces.Contains(race) || !ValidGenders.Contains(gender))
        {
            _logger.LogWarning("CharacterModelService: invalid race/gender '{Race}/{Gender}'", race, gender);
            return null;
        }

        // Normalize casing for filesystem consistency
        race = NormalizeRace(race);
        gender = NormalizeGender(gender);

        string key = race + gender;
        // Versioned filenames: bumping SkinnedGlbVersion invalidates all
        // cached character GLBs, bumping SkinPngVersion invalidates all
        // cached skin PNGs. CacheVersionRegistry.SweepAllOnStartup cleans
        // stale files at service boot. See that class for details.
        string glbFilename = CacheVersionRegistry.MakeVersioned(
            $"{key}.glb", CacheVersionRegistry.SkinnedGlbVersion);
        string glbPath = Path.Combine(CharacterModelsDir, glbFilename);
        string webUrl = $"/character_models/{glbFilename}";

        // Fast path: file already on disk
        if (File.Exists(glbPath))
            return webUrl;

        var sem = _locks.GetOrAdd(key, _ => new SemaphoreSlim(1, 1));
        await sem.WaitAsync();
        try
        {
            // Re-check after acquiring the lock — another request may have generated it
            if (File.Exists(glbPath))
                return webUrl;

            _logger.LogInformation("CharacterModelService: generating GLB for {Key}", key);

            // ── Extract M2 ──
            string m2MpqPath = $"Character\\{race}\\{gender}\\{race}{gender}.m2";
            byte[]? m2Bytes = _mpq.ExtractFile(m2MpqPath);
            if (m2Bytes == null)
            {
                // Try .MDX fallback (MPQ extension casing is unpredictable; ExtractModelFile handles this)
                m2Bytes = _mpq.ExtractModelFile(m2MpqPath);
            }
            if (m2Bytes == null)
            {
                _logger.LogError("CharacterModelService: MPQ extract failed for {Path}", m2MpqPath);
                return null;
            }

            // ── Parse ──
            var m2 = M2Reader.Parse(m2Bytes);
            if (m2 == null || !m2.IsValid)
            {
                _logger.LogError("CharacterModelService: M2Reader.Parse failed for {Path}", m2MpqPath);
                return null;
            }
            if (!m2.HasSkeleton)
            {
                _logger.LogError("CharacterModelService: character M2 has no skeleton — {Path}", m2MpqPath);
                return null;
            }

            // ── Extract default skin BLP ──
            // The character M2's texture array typically has a type-1 entry with an empty
            // filename — that's the body skin slot, which the WoW client fills with the
            // character's selected skin variant. For our default GLB we use Skin00_00.
            string skinMpqPath = $"Character\\{race}\\{gender}\\{race}{gender}Skin00_00.blp";
            byte[]? skinBlp = _mpq.ExtractFile(skinMpqPath);
            if (skinBlp == null)
            {
                _logger.LogWarning("CharacterModelService: no default skin BLP at {Path} — GLB will have fallback grey material", skinMpqPath);
            }

            // ── Build texture dictionary, slotting the skin into the type-1 slot ──
            // (Same approach ItemTextureService uses for weapons with DBC-resolved textures.)
            var textures = new Dictionary<int, byte[]>();
            if (skinBlp != null)
            {
                int skinSlot = FindSkinTextureSlot(m2);
                if (skinSlot >= 0)
                    textures[skinSlot] = skinBlp;
            }

            // ── Extract default hair BLP and bind to the type-6 slot ──
            //
            // Session S fix for the hair-textured-with-body-atlas bug.
            // Character M2s have a separate texture slot (Type=6,
            // TEX_COMPONENT_CHAR_HAIR) for the hair color BLP. Without it,
            // SkinnedGlbWriter's material assignment falls through to
            // materialsByTexIdx.Values.First() — the body atlas — and hair
            // geosets render with body-atlas UVs. Visible as a duplicate
            // face on Dwarf hair, body pixels on Tauren beard, etc.
            //
            // The hair partial path comes from CharSections.dbc (Hair row's
            // TextureName1). We use the same multi-candidate resolver the
            // face overlay uses, so DBC strings stored as full paths,
            // short refs, or bare names all resolve.
            uint raceId = RaceNameToId(race);
            uint sexId = gender.Equals("Female", StringComparison.OrdinalIgnoreCase) ? 1u : 0u;
            if (raceId > 0)
            {
                var hairRow = _dbcResolver.GetDefaultHairSection(raceId, sexId);
                if (hairRow != null && !string.IsNullOrEmpty(hairRow.TextureName1))
                {
                    var hairBlp = CharacterSkinCompositor.ResolveCharacterTextureBlp(
                        _mpq, hairRow.TextureName1, race, gender);
                    if (hairBlp != null)
                    {
                        int hairSlot = FindHairTextureSlot(m2);
                        if (hairSlot >= 0)
                        {
                            textures[hairSlot] = hairBlp;
                            _logger.LogInformation(
                                "CharacterModelService: bound hair BLP for {Key} slot={Slot} from '{Partial}'",
                                key, hairSlot, hairRow.TextureName1);
                        }
                        else
                        {
                            _logger.LogWarning(
                                "CharacterModelService: {Key} has no Type=6 (CHAR_HAIR) texture slot in M2 — hair will fall through to body atlas",
                                key);
                        }
                    }
                    else
                    {
                        _logger.LogWarning(
                            "CharacterModelService: hair BLP not in MPQ for {Key} — partial='{Partial}'",
                            key, hairRow.TextureName1);
                    }
                }
                else
                {
                    _logger.LogWarning(
                        "CharacterModelService: no Hair row in CharSections.dbc for {Key} (raceId={RaceId} sexId={SexId})",
                        key, raceId, sexId);
                }
            }

            // Also extract the skin PNG side-by-side for Session C texture compositing.
            // The web canvas compositor reads from /character_textures/skin/<key>Skin00_00.v{N}.png.
            // PNG is versioned independently of the GLB so a BLP-decode
            // change doesn't force GLB regeneration and vice versa.
            //
            // Session R: hand off to CharacterSkinCompositor, which layers
            // CharSections face textures onto FACE_LOWER and FACE_UPPER before
            // encoding. Bare-BLP fallback so a CharSections lookup failure
            // still produces a usable (if closed-eyed) PNG — better than an
            // empty file or a 404.
            if (skinBlp != null)
            {
                Directory.CreateDirectory(CharacterSkinsDir);
                var skinPngFilename = CacheVersionRegistry.MakeVersioned(
                    $"{key}Skin00_00.png", CacheVersionRegistry.SkinPngVersion);
                string skinPngPath = Path.Combine(CharacterSkinsDir, skinPngFilename);
                try
                {
                    var pngBytes = _skinCompositor.ComposeDefaultSkin(race, gender, skinBlp)
                                   ?? BlpToPng(skinBlp);
                    if (pngBytes != null)
                        await File.WriteAllBytesAsync(skinPngPath, pngBytes);
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "CharacterModelService: skin PNG export failed for {Key}", key);
                }
            }

            // ── Write the skinned GLB ──
            Directory.CreateDirectory(CharacterModelsDir);
            bool ok = SkinnedGlbWriter.SaveSkinnedGlb(m2, textures, glbPath);
            if (!ok)
            {
                _logger.LogError("CharacterModelService: SkinnedGlbWriter.SaveSkinnedGlb returned false for {Key}", key);
                return null;
            }

            _logger.LogInformation(
                "CharacterModelService: generated {Key}.glb — bones={Bones} attachments={Atts} verts={Verts}",
                key, m2.Bones.Count, m2.Attachments.Count, m2.Vertices.Count);

            return webUrl;
        }
        finally
        {
            sem.Release();
        }
    }

    /// <summary>
    /// Find the texture slot a character body skin should fill.
    ///
    /// Character M2s have a small (~3) texture array. Slot 0 is typically the
    /// body skin (type=1, empty filename). Type-1 means "client supplies the
    /// texture at runtime" — exactly the slot we need to populate.
    ///
    /// Returns the slot index, or -1 if no type-1 slot exists.
    /// </summary>
    private static int FindSkinTextureSlot(M2Model m2)
    {
        for (int i = 0; i < m2.Textures.Count; i++)
        {
            if (m2.Textures[i].Type == 1 && string.IsNullOrEmpty(m2.Textures[i].Filename))
                return i;
        }
        // Fallback: any type-1 slot
        for (int i = 0; i < m2.Textures.Count; i++)
        {
            if (m2.Textures[i].Type == 1)
                return i;
        }
        return -1;
    }

    /// <summary>
    /// Find the texture slot a character hair texture should fill.
    /// Type=6 is TEX_COMPONENT_CHAR_HAIR in the M2 type table — the hair
    /// color BLP that gets bound at runtime. Same "type N, empty filename"
    /// pattern as the skin slot.
    ///
    /// Returns the slot index, or -1 if no type-6 slot exists. (Some
    /// character M2s genuinely lack one — e.g. Tauren may key hair off
    /// type-8 SKIN_EXTRA for fur — and we let the caller decide what to
    /// do, rather than guessing.)
    /// </summary>
    private static int FindHairTextureSlot(M2Model m2)
    {
        for (int i = 0; i < m2.Textures.Count; i++)
        {
            if (m2.Textures[i].Type == 6 && string.IsNullOrEmpty(m2.Textures[i].Filename))
                return i;
        }
        for (int i = 0; i < m2.Textures.Count; i++)
        {
            if (m2.Textures[i].Type == 6)
                return i;
        }
        return -1;
    }

    /// <summary>
    /// Vanilla CharRaces.dbc IDs. Race names match NormalizeRace's output,
    /// so this is the same enum the rest of the pipeline uses.
    /// Returns 0 for unknown race name.
    /// </summary>
    private static uint RaceNameToId(string raceName) => raceName.ToLowerInvariant() switch
    {
        "human" => 1,
        "orc" => 2,
        "dwarf" => 3,
        "nightelf" => 4,
        "scourge" => 5,
        "undead" => 5,
        "tauren" => 6,
        "gnome" => 7,
        "troll" => 8,
        _ => 0u,
    };

    private static string NormalizeRace(string r)
    {
        return r.ToLowerInvariant() switch
        {
            "human" => "Human",
            "dwarf" => "Dwarf",
            "nightelf" => "NightElf",
            "gnome" => "Gnome",
            "orc" => "Orc",
            "tauren" => "Tauren",
            "troll" => "Troll",
            "scourge" => "Scourge",
            "undead" => "Scourge",  // accept either; MPQ folder is Scourge
            _ => r
        };
    }

    private static string NormalizeGender(string g) =>
        g.Equals("Female", StringComparison.OrdinalIgnoreCase) ? "Female" : "Male";

    /// <summary>
    /// BLP → PNG conversion using War3Net + SkiaSharp (Linux-safe).
    /// Inline copy because both writers also need this; avoids cross-coupling.
    /// </summary>
    private static byte[]? BlpToPng(byte[] blpData)
    {
        try
        {
            using var blpStream = new MemoryStream(blpData);
            var blpFile = new BlpFile(blpStream);
            var pixels = blpFile.GetPixels(0, out int w, out int h);
            if (w == 0 || h == 0 || pixels.Length == 0) return null;

            using var bitmap = new SkiaSharp.SKBitmap(w, h, SkiaSharp.SKColorType.Bgra8888, SkiaSharp.SKAlphaType.Unpremul);
            var bitmapPixels = bitmap.GetPixels();
            System.Runtime.InteropServices.Marshal.Copy(pixels, 0, bitmapPixels, pixels.Length);
            bitmap.NotifyPixelsChanged();

            using var pngStream = new MemoryStream();
            bitmap.Encode(pngStream, SkiaSharp.SKEncodedImageFormat.Png, 100);
            return pngStream.ToArray();
        }
        catch
        {
            return null;
        }
    }
}