using System.Text.Json;
using System.Text.Json.Serialization;

namespace MangosSuperUI.Services;

/// <summary>
/// Session 30: Spell Visual Knowledge Map
///
/// PURPOSE: Build and maintain a structured understanding of how spell visuals
/// work at the composition level. This is the "why" layer that sits between
/// raw M2 data and human intent.
///
/// THREE TIERS OF KNOWLEDGE:
///
/// ┌─────────────────────────────────────────────────────────────────────┐
/// │  Tier 1: EMITTER ARCHETYPES (the vocabulary)                       │
/// │                                                                     │
/// │  Named behavior patterns with parameter fingerprints.               │
/// │  Built empirically — we observe a pattern, name it, record the     │
/// │  parameter ranges that produce it.                                  │
/// │                                                                     │
/// │  Examples:                                                          │
/// │  • "upward_drift" — low speed, strong negative gravity, long life  │
/// │  • "imploding_gather" — negative speed, wide area, zero gravity    │
/// │  • "fast_scatter" — high speed, short life, wide angular range     │
/// │  • "dense_flicker" — high rate, very short life, tiny area         │
/// │  • "persistent_field" — long life, low speed, wide area            │
/// │  • "radial_burst" — plane emitter, wide area, short life           │
/// │                                                                     │
/// │  Each archetype defines what visual effect the emitter produces     │
/// │  and WHY those parameter values create that effect.                 │
/// ├─────────────────────────────────────────────────────────────────────┤
/// │  Tier 2: M2 PROFILES (the catalog)                                  │
/// │                                                                     │
/// │  A complete structural read of one M2 file: emitter count,          │
/// │  texture count, per-emitter archetype classification, per-texture   │
/// │  role assignment, and the emitter→texture wiring map.               │
/// │                                                                     │
/// │  This answers: "What does Fire_Precast_Hand.m2 actually do?"        │
/// │  → 5 emitters: [upward_drift, imploding_gather, glow_pulse,        │
/// │     glow_pulse, imploding_gather_wide]. 5 textures: [atlas_cloud,  │
/// │     body_core, glow_soft, body_mass, ribbon_trail].                 │
/// │  → Emitter 0 uses texture 2 (glow) + archetype upward_drift        │
/// │     = "rising glowing sparks"                                       │
/// │  → Emitter 1 uses texture 1 (body) + archetype imploding_gather    │
/// │     = "energy condensing into a ball"                               │
/// │                                                                     │
/// │  Profiles are auto-generated by scanning M2 bytes, then             │
/// │  manually enriched with archetype tags and descriptions after       │
/// │  in-game observation.                                               │
/// ├─────────────────────────────────────────────────────────────────────┤
/// │  Tier 3: SPELL DNA (the intent document)                            │
/// │                                                                     │
/// │  Maps human-readable creative intent to concrete M2+texture+emitter│
/// │  configuration. Each spell has a DNA document that says:            │
/// │                                                                     │
/// │  "I want [visual goal] → use [archetype] on emitter [N] with       │
/// │   texture role [X] because [why this combination works]"            │
/// │                                                                     │
/// │  The DNA document can COMPILE into a SpellTuningPreset JSON —       │
/// │  it's the design spec that the tuning system executes.              │
/// │                                                                     │
/// │  Every parameter value has a "why" annotation. Every time we        │
/// │  tune and observe, we update the why. This is how knowledge         │
/// │  accumulates across sessions.                                       │
/// └─────────────────────────────────────────────────────────────────────┘
///
/// STORAGE:
///   Archetypes:  /opt/mangossuperui/spelldna/archetypes.json
///   M2 Profiles: /opt/mangossuperui/spelldna/profiles/{filename}.json
///   Spell DNAs:  /opt/mangossuperui/spelldna/spells/{spellName}.json
///
/// DEPENDENCIES:
///   M2EmitterParser — reads emitter data from M2 bytes (read-only usage)
///   M2TextureParser — reads texture table from M2 bytes (read-only usage)
///   IConfiguration  — for base paths
///   ILogger         — diagnostics
///
/// This service does NOT modify M2 files, build patches, or touch DBC/SQL.
/// It is purely a knowledge store and classification engine.
/// </summary>
public class SpellDnaService
{
    private readonly IConfiguration _config;
    private readonly ILogger<SpellDnaService> _logger;

    // In-memory caches — loaded from disk at startup
    private readonly Dictionary<string, EmitterArchetype> _archetypes = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, M2Profile> _profiles = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, SpellDna> _spellDnas = new(StringComparer.OrdinalIgnoreCase);

    private string BasePath => _config["SpellCreator:DnaPath"]
        ?? "/opt/mangossuperui/spelldna";
    private string ArchetypesPath => Path.Combine(BasePath, "archetypes.json");
    private string ProfilesDir => Path.Combine(BasePath, "profiles");
    private string SpellDnaDir => Path.Combine(BasePath, "spells");
    private string SummariesDir => Path.Combine(BasePath, "summaries");

    public SpellDnaService(IConfiguration config, ILogger<SpellDnaService> logger)
    {
        _config = config;
        _logger = logger;
        LoadAll();
    }

    // ═══════════════════════════════════════════════════════════════
    //  STARTUP: Load everything from disk
    // ═══════════════════════════════════════════════════════════════

    private void LoadAll()
    {
        Directory.CreateDirectory(BasePath);
        Directory.CreateDirectory(ProfilesDir);
        Directory.CreateDirectory(SpellDnaDir);
        Directory.CreateDirectory(SummariesDir);

        LoadArchetypes();
        LoadProfiles();
        LoadSpellDnas();
    }

    private void LoadArchetypes()
    {
        if (!File.Exists(ArchetypesPath))
        {
            // Seed with initial archetypes derived from Fireball analysis
            SeedDefaultArchetypes();
            return;
        }

        try
        {
            var json = File.ReadAllText(ArchetypesPath);
            var list = JsonSerializer.Deserialize<List<EmitterArchetype>>(json, _jsonOpts);
            if (list != null)
            {
                foreach (var a in list)
                    _archetypes[a.Id] = a;
            }
            _logger.LogInformation("SpellDNA: Loaded {Count} archetypes", _archetypes.Count);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "SpellDNA: Failed to load archetypes, seeding defaults");
            SeedDefaultArchetypes();
        }
    }

    private void LoadProfiles()
    {
        if (!Directory.Exists(ProfilesDir)) return;

        foreach (var file in Directory.GetFiles(ProfilesDir, "*.json"))
        {
            try
            {
                var json = File.ReadAllText(file);
                var profile = JsonSerializer.Deserialize<M2Profile>(json, _jsonOpts);
                if (profile != null && !string.IsNullOrEmpty(profile.M2Filename))
                {
                    _profiles[profile.M2Filename] = profile;
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "SpellDNA: Failed to load profile {File}", Path.GetFileName(file));
            }
        }
        _logger.LogInformation("SpellDNA: Loaded {Count} M2 profiles", _profiles.Count);
    }

    private void LoadSpellDnas()
    {
        if (!Directory.Exists(SpellDnaDir)) return;

        foreach (var file in Directory.GetFiles(SpellDnaDir, "*.json"))
        {
            try
            {
                var json = File.ReadAllText(file);
                var dna = JsonSerializer.Deserialize<SpellDna>(json, _jsonOpts);
                if (dna != null && !string.IsNullOrEmpty(dna.SpellName))
                {
                    _spellDnas[dna.SpellName] = dna;
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "SpellDNA: Failed to load spell DNA {File}", Path.GetFileName(file));
            }
        }
        _logger.LogInformation("SpellDNA: Loaded {Count} spell DNAs", _spellDnas.Count);
    }

    // ═══════════════════════════════════════════════════════════════
    //  TIER 1: EMITTER ARCHETYPES
    // ═══════════════════════════════════════════════════════════════

    /// <summary>Get all known archetypes.</summary>
    public IReadOnlyDictionary<string, EmitterArchetype> GetArchetypes() => _archetypes;

    /// <summary>Get a specific archetype by ID.</summary>
    public EmitterArchetype? GetArchetype(string id)
        => _archetypes.TryGetValue(id, out var a) ? a : null;

    /// <summary>Add or update an archetype.</summary>
    public void SaveArchetype(EmitterArchetype archetype)
    {
        _archetypes[archetype.Id] = archetype;
        PersistArchetypes();
        _logger.LogInformation("SpellDNA: Saved archetype '{Id}'", archetype.Id);
    }

    /// <summary>Delete an archetype.</summary>
    public bool RemoveArchetype(string id)
    {
        if (!_archetypes.Remove(id)) return false;
        PersistArchetypes();
        return true;
    }

    /// <summary>
    /// Classify an emitter snapshot against known archetypes.
    /// Returns the best-matching archetype ID and a confidence score (0-1).
    /// Returns null if no archetype matches above the minimum threshold.
    /// </summary>
    public ArchetypeMatch? ClassifyEmitter(EmitterSnapshot emitter)
    {
        if (_archetypes.Count == 0) return null;

        ArchetypeMatch? best = null;

        foreach (var archetype in _archetypes.Values)
        {
            float score = ScoreArchetypeMatch(emitter, archetype);
            if (score > 0.3f && (best == null || score > best.Score))
            {
                best = new ArchetypeMatch
                {
                    ArchetypeId = archetype.Id,
                    ArchetypeName = archetype.Name,
                    Score = score
                };
            }
        }

        return best;
    }

    /// <summary>
    /// Score how well an emitter matches an archetype (0-1).
    ///
    /// For each parameter the archetype defines a range, we check whether
    /// the emitter's value falls within that range. Score = fraction of
    /// defined parameters that match.
    ///
    /// Special handling:
    ///   - Negative speed (imploding) vs positive speed (exploding) is a
    ///     categorical distinction, not just a range difference.
    ///   - EmitterType (point/sphere/plane) is a hard constraint when specified.
    ///   - BlendMode match is weighted but not disqualifying.
    /// </summary>
    private float ScoreArchetypeMatch(EmitterSnapshot emitter, EmitterArchetype archetype)
    {
        int checks = 0;
        int matches = 0;

        // Hard constraints — if these fail, score is 0
        if (archetype.RequiredEmitterType.HasValue)
        {
            if (emitter.EmitterType != archetype.RequiredEmitterType.Value)
                return 0f;
        }

        // Check each parameter fingerprint
        foreach (var fp in archetype.Fingerprint)
        {
            float? emitterValue = fp.Parameter switch
            {
                "emissionRate" => emitter.TrackValues.GetValueOrDefault("emissionRate"),
                "lifespan" => emitter.TrackValues.GetValueOrDefault("lifespan"),
                "emissionSpeed" => emitter.TrackValues.GetValueOrDefault("emissionSpeed"),
                "gravity" => emitter.TrackValues.GetValueOrDefault("gravity"),
                "emissionAreaLength" => emitter.TrackValues.GetValueOrDefault("emissionAreaLength"),
                "emissionAreaWidth" => emitter.TrackValues.GetValueOrDefault("emissionAreaWidth"),
                "verticalRange" => emitter.TrackValues.GetValueOrDefault("verticalRange"),
                "horizontalRange" => emitter.TrackValues.GetValueOrDefault("horizontalRange"),
                "speedVariation" => emitter.TrackValues.GetValueOrDefault("speedVariation"),
                "scaleStart" => emitter.ScaleStart,
                "scaleMid" => emitter.ScaleMid,
                "scaleEnd" => emitter.ScaleEnd,
                "blendMode" => emitter.BlendMode,
                _ => null
            };

            if (!emitterValue.HasValue) continue;

            checks++;
            float val = emitterValue.Value;

            // Check if value falls in the fingerprint range
            if (val >= fp.Min && val <= fp.Max)
                matches++;
            // Partial credit for being close (within 50% of range width)
            else
            {
                float rangeWidth = fp.Max - fp.Min;
                if (rangeWidth > 0)
                {
                    float distance = val < fp.Min ? fp.Min - val : val - fp.Max;
                    float tolerance = rangeWidth * 0.5f;
                    if (distance < tolerance)
                        matches++; // close enough
                }
            }
        }

        if (checks == 0) return 0f;
        return (float)matches / checks;
    }

    // ═══════════════════════════════════════════════════════════════
    //  TIER 2: M2 PROFILES
    // ═══════════════════════════════════════════════════════════════

    /// <summary>Get all loaded M2 profiles.</summary>
    public IReadOnlyDictionary<string, M2Profile> GetProfiles() => _profiles;

    /// <summary>Get a profile by M2 filename (case-insensitive).</summary>
    public M2Profile? GetProfile(string m2Filename)
        => _profiles.TryGetValue(m2Filename, out var p) ? p : null;

    /// <summary>
    /// Build an M2 profile from raw M2 bytes.
    /// Reads emitters and textures, classifies each emitter against known
    /// archetypes, maps emitter→texture wiring.
    ///
    /// The profile is returned but NOT auto-saved — the caller decides
    /// whether to persist (allows preview before committing).
    /// </summary>
    public M2Profile BuildProfile(byte[] m2Data, string m2Filename, string? m2RelativePath = null)
    {
        var emitters = M2EmitterParser.ReadEmitters(m2Data);
        var textures = M2TextureParser.ParseTextures(m2Data);

        var profile = new M2Profile
        {
            M2Filename = Path.GetFileName(m2Filename),
            M2Path = m2RelativePath ?? m2Filename,
            ScannedAt = DateTime.UtcNow,
            EmitterCount = emitters.Count,
            TextureCount = textures.Count,
        };

        // Build texture entries
        for (int i = 0; i < textures.Count; i++)
        {
            profile.Textures.Add(new ProfileTexture
            {
                Index = i,
                VanillaFilename = textures[i].Filename,
                // Role/description can be enriched later from recipes or manual annotation
            });
        }

        // Build emitter entries with archetype classification
        foreach (var em in emitters)
        {
            var match = ClassifyEmitter(em);

            var profileEmitter = new ProfileEmitter
            {
                Index = em.Index,
                TextureId = em.TextureId,
                BlendMode = em.BlendMode,
                EmitterType = em.EmitterType,

                // Raw values — the ground truth
                EmissionRate = em.TrackValues.GetValueOrDefault("emissionRate"),
                Lifespan = em.TrackValues.GetValueOrDefault("lifespan"),
                EmissionSpeed = em.TrackValues.GetValueOrDefault("emissionSpeed"),
                Gravity = em.TrackValues.GetValueOrDefault("gravity"),
                EmissionAreaLength = em.TrackValues.GetValueOrDefault("emissionAreaLength"),
                EmissionAreaWidth = em.TrackValues.GetValueOrDefault("emissionAreaWidth"),
                VerticalRange = em.TrackValues.GetValueOrDefault("verticalRange"),
                HorizontalRange = em.TrackValues.GetValueOrDefault("horizontalRange"),
                SpeedVariation = em.TrackValues.GetValueOrDefault("speedVariation"),
                ScaleStart = em.ScaleStart,
                ScaleMid = em.ScaleMid,
                ScaleEnd = em.ScaleEnd,

                // Classification
                ArchetypeId = match?.ArchetypeId,
                ArchetypeScore = match?.Score,
            };

            profile.Emitters.Add(profileEmitter);
        }

        // Wire up reverse references: which emitters point to each texture
        foreach (var tex in profile.Textures)
        {
            tex.ReferencedByEmitters = profile.Emitters
                .Where(e => e.TextureId == tex.Index)
                .Select(e => e.Index)
                .ToList();
        }

        return profile;
    }

    /// <summary>Save an M2 profile to disk.</summary>
    public void SaveProfile(M2Profile profile)
    {
        _profiles[profile.M2Filename] = profile;

        string safeName = SanitizeFilename(profile.M2Filename);
        string path = Path.Combine(ProfilesDir, $"{safeName}.json");
        File.WriteAllText(path, JsonSerializer.Serialize(profile, _jsonOpts));

        _logger.LogInformation("SpellDNA: Saved profile for '{M2}'", profile.M2Filename);
    }

    /// <summary>
    /// Batch-scan M2 files from a directory.
    /// Reads each .m2 file, builds a profile, classifies emitters.
    /// Returns profiles for all M2s that have at least one emitter.
    /// Does NOT auto-save — returns the list for review.
    /// </summary>
    public List<M2Profile> ScanDirectory(string m2Directory, string? subdirectory = null)
    {
        var results = new List<M2Profile>();

        string scanDir = subdirectory != null
            ? Path.Combine(m2Directory, subdirectory)
            : m2Directory;

        if (!Directory.Exists(scanDir))
        {
            _logger.LogWarning("SpellDNA: Scan directory not found: {Dir}", scanDir);
            return results;
        }

        var m2Files = Directory.GetFiles(scanDir, "*.m2", SearchOption.AllDirectories);
        _logger.LogInformation("SpellDNA: Scanning {Count} M2 files in {Dir}", m2Files.Length, scanDir);

        foreach (var filePath in m2Files)
        {
            try
            {
                var data = File.ReadAllBytes(filePath);
                string relativePath = Path.GetRelativePath(m2Directory, filePath);
                var profile = BuildProfile(data, filePath, relativePath);

                // Only keep M2s with emitters (skip meshes, attachments, etc.)
                if (profile.EmitterCount > 0)
                    results.Add(profile);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "SpellDNA: Failed to scan {File}", Path.GetFileName(filePath));
            }
        }

        _logger.LogInformation("SpellDNA: Scanned {Total} M2s, {WithEmitters} have emitters",
            m2Files.Length, results.Count);

        return results;
    }

    /// <summary>
    /// Save all profiles from a scan batch.
    /// </summary>
    public int SaveProfiles(List<M2Profile> profiles)
    {
        int saved = 0;
        foreach (var p in profiles)
        {
            SaveProfile(p);
            saved++;
        }
        return saved;
    }

    // ═══════════════════════════════════════════════════════════════
    //  TIER 3: SPELL DNA
    // ═══════════════════════════════════════════════════════════════

    /// <summary>Get all spell DNAs.</summary>
    public IReadOnlyDictionary<string, SpellDna> GetSpellDnas() => _spellDnas;

    /// <summary>Get a spell DNA by name.</summary>
    public SpellDna? GetSpellDna(string spellName)
        => _spellDnas.TryGetValue(spellName, out var dna) ? dna : null;

    /// <summary>Save a spell DNA to disk.</summary>
    public void SaveSpellDna(SpellDna dna)
    {
        _spellDnas[dna.SpellName] = dna;

        string safeName = SanitizeFilename(dna.SpellName);
        string path = Path.Combine(SpellDnaDir, $"{safeName}.json");
        File.WriteAllText(path, JsonSerializer.Serialize(dna, _jsonOpts));

        _logger.LogInformation("SpellDNA: Saved DNA for '{Spell}'", dna.SpellName);
    }

    /// <summary>
    /// Compile a SpellDna into a SpellTuningPreset.
    ///
    /// The DNA document is the design spec; the tuning preset is its
    /// compiled output. This bridges Tier 3 → the existing tuning system.
    ///
    /// Each SpellElement with emitter parameter overrides becomes an
    /// EmitterPatch in the preset. The "why" annotations are stripped
    /// since the tuning system doesn't use them.
    /// </summary>
    public SpellTuningPreset? CompileToPreset(SpellDna dna)
    {
        if (dna.Phases == null || dna.Phases.Count == 0) return null;

        var preset = new SpellTuningPreset
        {
            PresetName = $"{dna.SpellName}_dna_v{dna.Version}",
            SourceSpellEntry = dna.SourceSpellEntry,
            Theme = dna.Theme,
            Phases = new Dictionary<string, PhaseTuning>()
        };

        foreach (var (phaseKey, phaseDna) in dna.Phases)
        {
            var phaseTuning = new PhaseTuning
            {
                SourceM2 = phaseDna.SourceM2,
                Emitters = new List<EmitterPatch>(),
                Textures = new List<TextureTuning>()
            };

            if (phaseDna.Elements != null)
            {
                foreach (var element in phaseDna.Elements)
                {
                    // Build EmitterPatch from element's parameter overrides
                    if (element.Params != null && element.Params.Count > 0)
                    {
                        var patch = new EmitterPatch
                        {
                            EmitterIndex = element.EmitterIndex
                        };

                        foreach (var (paramName, annotated) in element.Params)
                        {
                            switch (paramName)
                            {
                                case "emissionRate": patch.EmissionRate = annotated.Value; break;
                                case "lifespan": patch.Lifespan = annotated.Value; break;
                                case "emissionSpeed": patch.EmissionSpeed = annotated.Value; break;
                                case "gravity": patch.Gravity = annotated.Value; break;
                                case "emissionAreaLength": patch.EmissionAreaLength = annotated.Value; break;
                                case "emissionAreaWidth": patch.EmissionAreaWidth = annotated.Value; break;
                                case "verticalRange": patch.VerticalRange = annotated.Value; break;
                                case "horizontalRange": patch.HorizontalRange = annotated.Value; break;
                                case "speedVariation": patch.SpeedVariation = annotated.Value; break;
                                case "scaleStart": patch.ScaleStart = annotated.Value; break;
                                case "scaleMid": patch.ScaleMid = annotated.Value; break;
                                case "scaleEnd": patch.ScaleEnd = annotated.Value; break;
                            }
                        }

                        phaseTuning.Emitters.Add(patch);
                    }

                    // Build TextureTuning from element's texture spec
                    if (element.Texture != null && !string.IsNullOrEmpty(element.Texture.SourcePng))
                    {
                        phaseTuning.Textures.Add(new TextureTuning
                        {
                            SlotIndex = element.Texture.TextureIndex,
                            SourcePng = element.Texture.SourcePng,
                            Role = element.Texture.Role ?? "Shape",
                            Density = element.Texture.Density,
                            FloorPercent = element.Texture.FloorPercent,
                            KneeWidth = element.Texture.KneeWidth,
                        });
                    }
                }
            }

            // Only add phase if it has content
            if (phaseTuning.Emitters.Count > 0 || phaseTuning.Textures.Count > 0)
                preset.Phases[phaseKey] = phaseTuning;
        }

        return preset;
    }

    /// <summary>
    /// Scaffold a SpellDna from an M2 profile + recipe.
    /// Creates a DNA document with all emitters and textures pre-populated
    /// from the profile's data, ready for the user to add intent descriptions
    /// and "why" annotations.
    ///
    /// This is the "I just scanned this M2, now give me a starting DNA template"
    /// workflow.
    /// </summary>
    public SpellDna ScaffoldDna(string spellName, int sourceSpellEntry,
        Dictionary<string, M2Profile> phaseProfiles, SpellRecipe? recipe = null)
    {
        var dna = new SpellDna
        {
            SpellName = spellName,
            SourceSpellEntry = sourceSpellEntry,
            CreatedAt = DateTime.UtcNow,
            Version = 1,
            Phases = new Dictionary<string, DnaPhase>()
        };

        foreach (var (phaseKey, profile) in phaseProfiles)
        {
            var dnaPhase = new DnaPhase
            {
                SourceM2 = profile.M2Path,
                Description = $"(describe the visual goal for the {phaseKey} phase)",
                Elements = new List<SpellElement>()
            };

            // Get recipe phase if available
            RecipePhase? recipePhase = null;
            recipe?.Phases.TryGetValue(phaseKey, out recipePhase);

            foreach (var em in profile.Emitters)
            {
                // Find the matching recipe slot for this emitter's texture
                RecipeTextureSlot? recipeSlot = recipePhase?.Slots
                    .FirstOrDefault(s => s.Index == em.TextureId);

                var element = new SpellElement
                {
                    Name = $"emitter_{em.Index}",
                    VisualGoal = "(describe what this particle element should look like)",
                    EmitterIndex = em.Index,
                    ArchetypeId = em.ArchetypeId,
                    Params = new Dictionary<string, AnnotatedValue>()
                };

                // Pre-populate params from profile values
                if (em.EmissionRate.HasValue)
                    element.Params["emissionRate"] = new AnnotatedValue
                    { Value = em.EmissionRate.Value, Why = null };
                if (em.Lifespan.HasValue)
                    element.Params["lifespan"] = new AnnotatedValue
                    { Value = em.Lifespan.Value, Why = null };
                if (em.EmissionSpeed.HasValue)
                    element.Params["emissionSpeed"] = new AnnotatedValue
                    { Value = em.EmissionSpeed.Value, Why = null };
                if (em.Gravity.HasValue)
                    element.Params["gravity"] = new AnnotatedValue
                    { Value = em.Gravity.Value, Why = null };
                if (em.EmissionAreaLength.HasValue)
                    element.Params["emissionAreaLength"] = new AnnotatedValue
                    { Value = em.EmissionAreaLength.Value, Why = null };
                if (em.EmissionAreaWidth.HasValue)
                    element.Params["emissionAreaWidth"] = new AnnotatedValue
                    { Value = em.EmissionAreaWidth.Value, Why = null };

                element.Params["scaleStart"] = new AnnotatedValue
                { Value = em.ScaleStart, Why = null };
                element.Params["scaleMid"] = new AnnotatedValue
                { Value = em.ScaleMid, Why = null };
                element.Params["scaleEnd"] = new AnnotatedValue
                { Value = em.ScaleEnd, Why = null };

                // Texture spec from recipe or profile
                element.Texture = new ElementTexture
                {
                    TextureIndex = em.TextureId,
                    Role = recipeSlot?.Role,
                    Job = recipeSlot?.Job,
                    Density = recipeSlot?.Density,
                    VanillaFilename = profile.Textures
                        .FirstOrDefault(t => t.Index == em.TextureId)?.VanillaFilename,
                };

                dnaPhase.Elements.Add(element);
            }

            dna.Phases[phaseKey] = dnaPhase;
        }

        return dna;
    }

    // ═══════════════════════════════════════════════════════════════
    //  SEED: Default archetypes from Fireball analysis
    // ═══════════════════════════════════════════════════════════════

    private void SeedDefaultArchetypes()
    {
        var defaults = new List<EmitterArchetype>
        {
            new()
            {
                Id = "upward_drift",
                Name = "Upward Drift",
                Description = "Particles float upward from a point source, shrinking as they rise. " +
                    "Creates 'rising sparks' or 'ascending embers' effect. Low emission speed " +
                    "means particles don't fly outward — negative gravity pulls them up.",
                VisualResult = "Rising, shrinking sparks that drift upward from the cast point",
                ExampleSpells = new List<string> { "Fireball precast emitter 0" },
                Fingerprint = new List<ParamFingerprint>
                {
                    new() { Parameter = "emissionSpeed", Min = 0.05f, Max = 0.5f, Significance = "Low speed = particles barely move on their own" },
                    new() { Parameter = "gravity", Min = -6.0f, Max = -1.0f, Significance = "Strong negative = upward pull" },
                    new() { Parameter = "lifespan", Min = 0.4f, Max = 1.2f, Significance = "Long enough to see the drift" },
                    new() { Parameter = "emissionRate", Min = 20f, Max = 60f, Significance = "Moderate density — visible but not solid" },
                    new() { Parameter = "scaleEnd", Min = 0.01f, Max = 0.08f, Significance = "Shrinks to near-nothing = fade-out feel" },
                },
                RequiredEmitterType = 0, // point
            },

            new()
            {
                Id = "imploding_gather",
                Name = "Imploding Gather",
                Description = "Particles spawn across a wide area and suck inward (negative speed). " +
                    "Creates 'energy condensing' or 'gathering power' effect. Wide emission area " +
                    "gives the spawn volume; negative speed pulls everything to center.",
                VisualResult = "Energy converging inward from a cloud into a tight point",
                ExampleSpells = new List<string> { "Fireball precast emitter 1", "Fireball precast emitter 4" },
                Fingerprint = new List<ParamFingerprint>
                {
                    new() { Parameter = "emissionSpeed", Min = -3.0f, Max = -0.5f, Significance = "Negative = inward pull" },
                    new() { Parameter = "gravity", Min = -0.5f, Max = 0.5f, Significance = "Near-zero — motion is from speed, not gravity" },
                    new() { Parameter = "emissionAreaLength", Min = 0.2f, Max = 1.0f, Significance = "Wide spawn area = visible convergence volume" },
                    new() { Parameter = "emissionRate", Min = 40f, Max = 80f, Significance = "High density = solid-looking gather" },
                    new() { Parameter = "lifespan", Min = 0.3f, Max = 0.7f, Significance = "Short-medium — particles don't linger" },
                    new() { Parameter = "scaleStart", Min = 0.02f, Max = 0.08f, Significance = "Small particles = energy wisps" },
                },
            },

            new()
            {
                Id = "glow_pulse",
                Name = "Glow Pulse",
                Description = "Low-rate, very short-lived particles at a point source with large " +
                    "constant scale. Creates a pulsing glow that stays in place — the particle " +
                    "sprites overlap to form a steady luminous region.",
                VisualResult = "Steady glowing aura or pulsing light at the cast point",
                ExampleSpells = new List<string> { "Fireball precast emitters 2 & 3" },
                Fingerprint = new List<ParamFingerprint>
                {
                    new() { Parameter = "emissionRate", Min = 5f, Max = 20f, Significance = "Low rate — glow doesn't need many particles" },
                    new() { Parameter = "lifespan", Min = 0.1f, Max = 0.4f, Significance = "Very short — constant replacement = steady glow" },
                    new() { Parameter = "emissionSpeed", Min = -0.1f, Max = 0.1f, Significance = "Near-zero — stays in place" },
                    new() { Parameter = "scaleStart", Min = 0.3f, Max = 1.0f, Significance = "Large = covers area as a glow, not a particle" },
                    new() { Parameter = "gravity", Min = -0.5f, Max = 0.5f, Significance = "Near-zero — no drift" },
                },
                RequiredEmitterType = 0,
            },

            new()
            {
                Id = "fast_scatter",
                Name = "Fast Scatter",
                Description = "Particles shoot outward rapidly in all directions with short lifespan. " +
                    "Creates 'sparks flying' or 'electric arcs escaping' effect. High speed + " +
                    "wide angular range + short life = snappy outward burst.",
                VisualResult = "Sparks or arcs shooting outward rapidly in all directions",
                ExampleSpells = new List<string> { "Lightning Bolt (hypothesized)" },
                Fingerprint = new List<ParamFingerprint>
                {
                    new() { Parameter = "emissionSpeed", Min = 2.0f, Max = 7.0f, Significance = "High speed = fast outward travel" },
                    new() { Parameter = "lifespan", Min = 0.1f, Max = 0.35f, Significance = "Very short = snappy, doesn't linger" },
                    new() { Parameter = "emissionRate", Min = 30f, Max = 80f, Significance = "High rate = dense burst" },
                    new() { Parameter = "verticalRange", Min = 2.0f, Max = 3.15f, Significance = "Wide spread = all directions" },
                    new() { Parameter = "horizontalRange", Min = 2.0f, Max = 6.3f, Significance = "Wide spread = all directions" },
                    new() { Parameter = "scaleStart", Min = 0.03f, Max = 0.15f, Significance = "Small = individual sparks, not clouds" },
                },
            },

            new()
            {
                Id = "dense_flicker",
                Name = "Dense Flicker",
                Description = "Very high emission rate with very short lifespan from a point. " +
                    "Particles die almost instantly but are replaced so fast they form a " +
                    "solid-looking mass that flickers. Like a torch flame.",
                VisualResult = "Solid flickering mass — concentrated energy ball or flame core",
                ExampleSpells = new List<string> { "(compose for Chidori-style core)" },
                Fingerprint = new List<ParamFingerprint>
                {
                    new() { Parameter = "emissionRate", Min = 60f, Max = 120f, Significance = "Very high = particles overlap into solid mass" },
                    new() { Parameter = "lifespan", Min = 0.05f, Max = 0.2f, Significance = "Extremely short = constant flicker" },
                    new() { Parameter = "emissionSpeed", Min = 0.0f, Max = 0.3f, Significance = "Near-zero = stays at origin" },
                    new() { Parameter = "emissionAreaLength", Min = 0.0f, Max = 0.05f, Significance = "Tiny area = concentrated point" },
                    new() { Parameter = "scaleStart", Min = 0.15f, Max = 0.4f, Significance = "Medium = visible core" },
                },
                RequiredEmitterType = 0,
            },

            new()
            {
                Id = "radial_burst",
                Name = "Radial Burst",
                Description = "Plane emitter with wide area, short life, moderate speed. " +
                    "Creates a ring or disc of particles that expand outward. " +
                    "Impact novas, holy novas, thunderclap rings.",
                VisualResult = "Expanding ring or disc of particles (nova/shockwave)",
                ExampleSpells = new List<string> { "Frost Nova, Holy Nova (hypothesized)" },
                Fingerprint = new List<ParamFingerprint>
                {
                    new() { Parameter = "emissionRate", Min = 30f, Max = 80f, Significance = "High burst to fill the ring" },
                    new() { Parameter = "lifespan", Min = 0.3f, Max = 0.6f, Significance = "Short — burst, not lingering" },
                    new() { Parameter = "emissionSpeed", Min = 1.0f, Max = 5.0f, Significance = "Outward expansion" },
                    new() { Parameter = "emissionAreaLength", Min = 0.3f, Max = 1.0f, Significance = "Wide spawn = ring shape" },
                    new() { Parameter = "emissionAreaWidth", Min = 0.3f, Max = 1.0f, Significance = "Wide spawn = ring shape" },
                },
                RequiredEmitterType = 2, // plane
            },

            new()
            {
                Id = "lingering_field",
                Name = "Lingering Field",
                Description = "Long-lived particles with low speed, wide area, little gravity. " +
                    "Creates a persistent cloud or ground effect. Consecration, Blizzard, " +
                    "Rain of Fire ground patches.",
                VisualResult = "Persistent cloud or ground effect that hangs in place",
                ExampleSpells = new List<string> { "Consecration, Blizzard (hypothesized)" },
                Fingerprint = new List<ParamFingerprint>
                {
                    new() { Parameter = "lifespan", Min = 0.8f, Max = 3.0f, Significance = "Long life = persistent" },
                    new() { Parameter = "emissionSpeed", Min = 0.0f, Max = 0.5f, Significance = "Low = stays in place" },
                    new() { Parameter = "gravity", Min = -1.0f, Max = 1.0f, Significance = "Mild or none — no strong drift" },
                    new() { Parameter = "emissionAreaLength", Min = 0.3f, Max = 1.0f, Significance = "Wide area = fills a zone" },
                    new() { Parameter = "emissionRate", Min = 10f, Max = 40f, Significance = "Moderate — long life means fewer needed" },
                },
            },
        };

        foreach (var a in defaults)
            _archetypes[a.Id] = a;

        PersistArchetypes();
        _logger.LogInformation("SpellDNA: Seeded {Count} default archetypes", defaults.Count);
    }

    // ═══════════════════════════════════════════════════════════════
    //  EXPERIMENT ENGINE: Systematic parameter sweep planning
    //
    //  Given a source spell's emitter data (per phase), generates an
    //  experiment batch: N spell clone plans, each changing 1 emitter
    //  per phase (so 3-4 observations per clone, no cross-pollution).
    //
    //  The engine doesn't clone spells or patch M2s — it produces
    //  ExperimentPlan objects. PatchController executes them.
    // ═══════════════════════════════════════════════════════════════

    // ── Experiment Summary persistence ──

    /// <summary>Load experiment summary for a spell. Returns null if none exists.</summary>
    public ExperimentSummary? GetSummary(string spellName)
    {
        string path = Path.Combine(SummariesDir, SanitizeFilename(spellName) + ".json");
        if (!File.Exists(path)) return null;
        try
        {
            return JsonSerializer.Deserialize<ExperimentSummary>(File.ReadAllText(path), _jsonOpts);
        }
        catch { return null; }
    }

    /// <summary>Save or update an experiment summary.</summary>
    public void SaveSummary(ExperimentSummary summary)
    {
        Directory.CreateDirectory(SummariesDir);
        string path = Path.Combine(SummariesDir, SanitizeFilename(summary.SpellName) + ".json");
        File.WriteAllText(path, JsonSerializer.Serialize(summary, _jsonOpts));
        _logger.LogInformation("SpellDNA: Saved experiment summary for {Spell} ({Batches} batches)",
            summary.SpellName, summary.Batches.Count);
    }

    /// <summary>List all spell names that have experiment summaries.</summary>
    public List<string> ListSummaries()
    {
        if (!Directory.Exists(SummariesDir)) return new();
        return Directory.GetFiles(SummariesDir, "*.json")
            .Select(f => Path.GetFileNameWithoutExtension(f))
            .ToList();
    }

    /// <summary>
    /// Determine which emitter index to target next for a spell, based on
    /// what's already been tested. Returns the emitter index and the reason.
    /// </summary>
    public (int emitterIndex, string reason) PickNextEmitter(
        string spellName,
        List<EmitterSnapshot> phaseEmitters)
    {
        var summary = GetSummary(spellName);
        if (summary == null || summary.Batches.Count == 0)
        {
            // First batch: pick highest-rate emitter
            var best = phaseEmitters
                .OrderByDescending(e => e.TrackValues.GetValueOrDefault("emissionRate") ?? 0)
                .First();
            return (best.Index, $"First batch — highest emission rate (emitter {best.Index})");
        }

        // Find which emitter indices have already been tested
        var testedEmitters = summary.Batches
            .Select(b => b.EmitterTargeted)
            .ToHashSet();

        // All available emitter indices
        var allIndices = phaseEmitters.Select(e => e.Index).Distinct().OrderBy(i => i).ToList();

        // Find untested emitters
        var untested = allIndices.Where(i => !testedEmitters.Contains(i)).ToList();

        if (untested.Count == 0)
        {
            // All emitters tested — suggest re-running highest-impact one or different spell
            return (allIndices[0], $"All {allIndices.Count} emitters already tested. Re-running emitter 0 or try a different spell.");
        }

        // Pick next untested, prefer by emission rate
        var nextEmitter = phaseEmitters
            .Where(e => untested.Contains(e.Index))
            .OrderByDescending(e => e.TrackValues.GetValueOrDefault("emissionRate") ?? 0)
            .First();

        return (nextEmitter.Index, $"Batch {summary.Batches.Count + 1} — emitter {nextEmitter.Index} (untested, {testedEmitters.Count}/{allIndices.Count} done)");
    }

    /// <summary>
    /// Parameters we sweep and their test value strategies.
    ///
    /// Each SweepParam defines how to generate test values for one
    /// emitter property. The strategy is "meaningful deltas from baseline"
    /// — not linear interpolation, but jumps that produce visible changes.
    ///
    /// The values are computed as multipliers or absolute offsets from
    /// the emitter's current value, depending on the parameter.
    /// </summary>
    private static readonly SweepParamDef[] SweepParams = new[]
    {
        // Rate: controls particle density. 2x = noticeably denser, 0.25x = sparse
        new SweepParamDef("emissionRate", SweepMode.Multiply,
            new float[] { 0.25f, 0.5f, 2.0f, 4.0f },
            "Particle density — how many per second"),

        // Lifespan: controls how long particles live. Shorter = snappier, longer = lingering
        new SweepParamDef("lifespan", SweepMode.Multiply,
            new float[] { 0.3f, 0.5f, 2.0f, 3.0f },
            "Particle lifetime — short=snappy, long=lingering"),

        // Speed: controls how fast particles move. Negative = inward
        new SweepParamDef("emissionSpeed", SweepMode.Absolute,
            new float[] { 0.0f, 0.5f, 2.0f, 5.0f, -1.0f, -3.0f },
            "Movement speed — positive=outward, negative=inward, zero=stationary"),

        // Gravity: negative = upward, positive = downward
        new SweepParamDef("gravity", SweepMode.Absolute,
            new float[] { 0.0f, -1.0f, -5.0f, 2.0f, 5.0f },
            "Gravity — negative=rises, positive=falls, zero=floats"),

        // Scale: controls particle size. Bigger = more prominent
        new SweepParamDef("scaleStart", SweepMode.Multiply,
            new float[] { 0.25f, 0.5f, 2.0f, 4.0f },
            "Particle start size — bigger=more prominent"),

        // Area: controls spawn volume. Wider = more spread out
        new SweepParamDef("emissionAreaLength", SweepMode.Multiply,
            new float[] { 0.1f, 0.5f, 3.0f, 8.0f },
            "Spawn area — wider=spread out, narrow=concentrated"),
    };

    /// <summary>
    /// Plan an experiment batch for a source spell.
    ///
    /// For each phase, picks a target emitter (the most "interesting" one —
    /// highest emission rate, or the one with most visual impact).
    ///
    /// Generates N experiment plans where each plan changes one parameter
    /// per phase. The plans cycle through parameters and test values so
    /// the full batch covers the parameter space systematically.
    ///
    /// Returns the plans — caller (PatchController) executes them by
    /// cloning spells and patching M2s.
    /// </summary>
    /// <param name="phaseEmitters">Per-phase emitter snapshots from M2EmitterParser.ReadEmitters()</param>
    /// <param name="sourceSpellEntry">Source spell entry ID</param>
    /// <param name="sourceSpellName">Source spell name for labeling</param>
    /// <param name="batchSize">How many clones to generate (default 20)</param>
    /// <param name="targetEmitters">Optional: specific emitter index to target per phase.
    /// If null, auto-selects the highest-rate emitter per phase.</param>
    public ExperimentBatch PlanExperiments(
        Dictionary<string, List<EmitterSnapshot>> phaseEmitters,
        int sourceSpellEntry,
        string sourceSpellName,
        int batchSize = 20,
        Dictionary<string, int>? targetEmitters = null)
    {
        var batch = new ExperimentBatch
        {
            SourceSpellEntry = sourceSpellEntry,
            SourceSpellName = sourceSpellName,
            CreatedAt = DateTime.UtcNow,
            Plans = new List<ExperimentPlan>()
        };

        // Determine which phases have emitters to work with
        var activePhases = phaseEmitters
            .Where(kv => kv.Value.Count > 0)
            .ToDictionary(kv => kv.Key, kv => kv.Value);

        if (activePhases.Count == 0) return batch;

        // Pick target emitter per phase
        var targets = new Dictionary<string, EmitterSnapshot>();
        foreach (var (phase, emitters) in activePhases)
        {
            int targetIdx = 0;
            if (targetEmitters != null && targetEmitters.TryGetValue(phase, out int specified))
            {
                targetIdx = specified;
            }
            else
            {
                // Auto-select: pick the emitter with highest emission rate
                // (most visually prominent, changes will be most visible)
                var best = emitters
                    .OrderByDescending(e => e.TrackValues.GetValueOrDefault("emissionRate") ?? 0)
                    .First();
                targetIdx = best.Index;
            }

            var target = emitters.FirstOrDefault(e => e.Index == targetIdx);
            if (target != null)
                targets[phase] = target;
        }

        if (targets.Count == 0) return batch;

        // Build the sweep schedule: distribute parameters across clones
        // so each clone varies a different param per phase
        var phaseKeys = targets.Keys.OrderBy(k => k).ToList();
        int paramCount = SweepParams.Length;

        // For each clone, assign one parameter+value per phase
        // Phase 0 gets param[cloneIdx % paramCount], value[cloneIdx / paramCount % valueCount]
        // Phase 1 gets a different param offset so phases don't repeat the same param
        for (int cloneIdx = 0; cloneIdx < batchSize; cloneIdx++)
        {
            var plan = new ExperimentPlan
            {
                CloneIndex = cloneIdx + 1,
                PhaseChanges = new Dictionary<string, ExperimentPhaseChange>()
            };

            var descParts = new List<string>();

            for (int phaseOrdinal = 0; phaseOrdinal < phaseKeys.Count; phaseOrdinal++)
            {
                string phase = phaseKeys[phaseOrdinal];
                var emitter = targets[phase];

                // Offset the parameter selection per phase so we get variety
                int paramIdx = (cloneIdx + phaseOrdinal) % paramCount;
                var sweepDef = SweepParams[paramIdx];

                // Cycle through test values for this parameter
                int valueIdx = ((cloneIdx + phaseOrdinal) / paramCount) % sweepDef.TestValues.Length;
                float testValue = sweepDef.TestValues[valueIdx];

                // Get baseline value
                float? baseline = sweepDef.ParamName switch
                {
                    "scaleStart" => emitter.ScaleStart,
                    _ => emitter.TrackValues.GetValueOrDefault(sweepDef.ParamName)
                };

                if (!baseline.HasValue) continue;

                // Compute new value
                float newValue = sweepDef.Mode == SweepMode.Multiply
                    ? baseline.Value * testValue
                    : testValue;

                // Skip if the change is negligible
                if (Math.Abs(newValue - baseline.Value) < 0.001f) continue;

                // Round for readability
                newValue = MathF.Round(newValue, 3);

                var change = new ExperimentPhaseChange
                {
                    Phase = phase,
                    EmitterIndex = emitter.Index,
                    Parameter = sweepDef.ParamName,
                    BaselineValue = baseline.Value,
                    NewValue = newValue,
                    Mode = sweepDef.Mode == SweepMode.Multiply
                        ? $"×{testValue}"
                        : $"={testValue}",
                    ParameterDescription = sweepDef.Description,
                };

                plan.PhaseChanges[phase] = change;
                descParts.Add($"{phase}/em{emitter.Index}: {sweepDef.ParamName} {baseline.Value:F2}→{newValue:F2}");
            }

            if (descParts.Count == 0) continue;

            // Build the description that goes into spell_template.description
            plan.SpellDescription = $"[EXP #{cloneIdx + 1}] {string.Join(" | ", descParts)}";
            plan.SpellName = $"{sourceSpellName} E{cloneIdx + 1:D2}";

            batch.Plans.Add(plan);
        }

        batch.TotalObservations = batch.Plans.Sum(p => p.PhaseChanges.Count);
        return batch;
    }

    // ═══════════════════════════════════════════════════════════════
    //  EXTREME EXPERIMENT ENGINE
    //
    //  "Bigger swings, fewer clones" — designed to produce clearly
    //  visible differences. Two clones per parameter:
    //    SUPPRESS = near-zero / opposite extreme
    //    CRANK    = 10x / max extreme
    //
    //  Key difference from standard sweep:
    //    - Same parameter changed in ALL phases simultaneously
    //      (so you see the effect everywhere, not isolated per phase)
    //    - Only 2 values per param = 12 clones total
    //    - Labels are human-readable: "Fireball X01 ZERO rate"
    // ═══════════════════════════════════════════════════════════════

    private static readonly ExtremeParamDef[] ExtremeParams = new[]
    {
        new ExtremeParamDef("emissionRate", SweepMode.Multiply,
            suppressMultiplier: 0.05f, crankMultiplier: 10.0f,
            suppressLabel: "ZERO rate", crankLabel: "MAX rate",
            description: "Particle density — near-invisible vs solid mass"),

        new ExtremeParamDef("lifespan", SweepMode.Multiply,
            suppressMultiplier: 0.1f, crankMultiplier: 8.0f,
            suppressLabel: "FLASH life", crankLabel: "LINGER life",
            description: "Particle lifetime — instant flash vs long trails"),

        new ExtremeParamDef("emissionSpeed", SweepMode.Absolute,
            suppressAbsolute: 0.0f, crankAbsolute: 8.0f,
            suppressLabel: "STILL speed", crankLabel: "BLAST speed",
            description: "Movement speed — frozen in place vs explosive outward"),

        new ExtremeParamDef("gravity", SweepMode.Absolute,
            suppressAbsolute: -10.0f, crankAbsolute: 10.0f,
            suppressLabel: "RISE grav", crankLabel: "FALL grav",
            description: "Gravity — strong upward pull vs heavy downward"),

        new ExtremeParamDef("scaleStart", SweepMode.Multiply,
            suppressMultiplier: 0.1f, crankMultiplier: 8.0f,
            suppressLabel: "TINY scale", crankLabel: "HUGE scale",
            description: "Particle size — pinpoint vs enormous"),

        new ExtremeParamDef("emissionAreaLength", SweepMode.Multiply,
            suppressMultiplier: 0.05f, crankMultiplier: 10.0f,
            suppressLabel: "POINT area", crankLabel: "WIDE area",
            description: "Spawn volume — concentrated point vs wide spread"),

        new ExtremeParamDef("speedVariation", SweepMode.Absolute,
            suppressAbsolute: 0.0f, crankAbsolute: 1.0f,
            suppressLabel: "UNIFORM spdVar", crankLabel: "CHAOTIC spdVar",
            description: "Speed randomness — all particles same speed vs wildly varied"),

        new ExtremeParamDef("verticalRange", SweepMode.Absolute,
            suppressAbsolute: 0.01f, crankAbsolute: 6.283f,
            suppressLabel: "FLAT vRange", crankLabel: "SPHERE vRange",
            description: "Vertical emission angle — flat plane vs full sphere (PI=hemisphere, 2PI=sphere)"),

        new ExtremeParamDef("horizontalRange", SweepMode.Absolute,
            suppressAbsolute: 0.01f, crankAbsolute: 6.283f,
            suppressLabel: "NARROW hRange", crankLabel: "FULL hRange",
            description: "Horizontal emission angle — tight beam vs full 360 (2PI=full circle)"),
    };

    /// <summary>
    /// Plan an extreme experiment batch with SMART deduplication.
    ///
    /// Instead of "pick one emitter, test all 9 params," this scans ALL
    /// emitters across ALL phases, builds a list of untested (phase, emitter,
    /// param) combos, deduplicates by baseline similarity (skip if baseline
    /// within 10% of an already-tested one for that param), and generates
    /// clones that test novel combos.
    ///
    /// Each clone still tests ONE parameter with suppress+crank extremes,
    /// but the emitter targeted CAN DIFFER per phase within a clone.
    /// For each parameter, the planner picks the most "interesting" untested
    /// emitter per phase (the one whose baseline is most different from
    /// already-tested baselines).
    ///
    /// Max 18 clones (9 params × 2 extremes). If some params have no novel
    /// combos left, fewer clones are generated.
    /// </summary>
    public ExperimentBatch PlanExtremeExperiments(
        Dictionary<string, List<EmitterSnapshot>> phaseEmitters,
        int sourceSpellEntry,
        string sourceSpellName,
        Dictionary<string, int>? targetEmitters = null)
    {
        var batch = new ExperimentBatch
        {
            SourceSpellEntry = sourceSpellEntry,
            SourceSpellName = sourceSpellName,
            CreatedAt = DateTime.UtcNow,
            Plans = new List<ExperimentPlan>()
        };

        var activePhases = phaseEmitters
            .Where(kv => kv.Value.Count > 0)
            .ToDictionary(kv => kv.Key, kv => kv.Value);

        if (activePhases.Count == 0) return batch;

        // ── Step 1: Load all previously tested combos ──
        var summary = GetSummary(sourceSpellName);
        var testedCombos = new List<TestedCombo>();
        if (summary != null)
        {
            foreach (var b in summary.Batches)
            {
                if (b.TestedCombos != null && b.TestedCombos.Count > 0)
                {
                    testedCombos.AddRange(b.TestedCombos);
                }
                else if (b.Findings?.PerParameter != null && b.PhasesFound?.Count > 0)
                {
                    // Synthetic combos from Claude quantization batches that have findings
                    // but no explicit TestedCombos (imported via AppendBatchSummary).
                    // For each parameter in findings, mark it as tested for emitterTargeted
                    // in every phase that was found in this batch.
                    foreach (var paramName in b.Findings.PerParameter.Keys)
                    {
                        foreach (var phase in b.PhasesFound)
                        {
                            // Try to find the baseline from the phase emitters if available
                            float baseline = 0f;
                            if (phaseEmitters.TryGetValue(phase, out var emitters))
                            {
                                var em = emitters.FirstOrDefault(e => e.Index == b.EmitterTargeted);
                                if (em != null)
                                {
                                    baseline = paramName == "scaleStart"
                                        ? em.ScaleStart
                                        : em.TrackValues.GetValueOrDefault(paramName) ?? 0f;
                                }
                            }

                            testedCombos.Add(new TestedCombo
                            {
                                Phase = phase,
                                EmitterIndex = b.EmitterTargeted,
                                Parameter = paramName,
                                Baseline = baseline
                            });
                        }
                    }
                    _logger.LogInformation(
                        "SpellDNA: Synthesized {Count} TestedCombos from batch {Id} findings for {Spell}",
                        b.Findings.PerParameter.Count * b.PhasesFound.Count, b.BatchId, sourceSpellName);
                }
            }
        }

        // ── Step 2: For each param, find the best untested emitter per phase ──
        var paramPhaseTargets = new Dictionary<string, Dictionary<string, EmitterSnapshot>>();
        var paramReasons = new Dictionary<string, string>();
        int totalNovel = 0;

        foreach (var extremeDef in ExtremeParams)
        {
            var phaseTargets = new Dictionary<string, EmitterSnapshot>();
            int novelCount = 0;

            foreach (var (phase, emitters) in activePhases)
            {
                // If manual override, use it
                if (targetEmitters != null && targetEmitters.TryGetValue(phase, out int specified))
                {
                    var target = emitters.FirstOrDefault(e => e.Index == specified);
                    if (target != null) phaseTargets[phase] = target;
                    continue;
                }

                // Find untested emitters for this param+phase combo
                var candidates = new List<(EmitterSnapshot emitter, float baseline, float novelty)>();

                foreach (var emitter in emitters)
                {
                    float? baseline = extremeDef.ParamName switch
                    {
                        "scaleStart" => emitter.ScaleStart,
                        _ => emitter.TrackValues.GetValueOrDefault(extremeDef.ParamName)
                    };
                    if (!baseline.HasValue) continue;

                    // Check if this baseline was already tested for this param
                    bool alreadyTested = testedCombos.Any(tc =>
                        tc.Phase == phase &&
                        tc.Parameter == extremeDef.ParamName &&
                        IsBaselineSimilar(tc.Baseline, baseline.Value));

                    if (!alreadyTested)
                    {
                        // Novelty = how different this baseline is from all tested baselines
                        float novelty = ComputeNovelty(baseline.Value, extremeDef.ParamName, phase, testedCombos);
                        candidates.Add((emitter, baseline.Value, novelty));
                    }
                }

                if (candidates.Count > 0)
                {
                    // Pick the most novel candidate
                    var best = candidates.OrderByDescending(c => c.novelty).First();
                    phaseTargets[phase] = best.emitter;
                    novelCount++;
                }
                else
                {
                    // All emitters tested for this param in this phase — pick highest-rate as fallback
                    // but mark as not novel (won't affect clone count)
                    var fallback = emitters
                        .OrderByDescending(e => e.TrackValues.GetValueOrDefault("emissionRate") ?? 0)
                        .First();
                    phaseTargets[phase] = fallback;
                }
            }

            if (phaseTargets.Count > 0)
            {
                paramPhaseTargets[extremeDef.ParamName] = phaseTargets;
                if (novelCount > 0)
                {
                    totalNovel++;
                    paramReasons[extremeDef.ParamName] = $"{novelCount} phase(s) with untested emitters";
                }
                else
                {
                    paramReasons[extremeDef.ParamName] = "all baselines already tested (re-run)";
                }
            }
        }

        // ── Step 3: Build clone plans — only for params with novel combos ──
        int cloneNum = 0;
        var reasonParts = new List<string>();

        foreach (var extremeDef in ExtremeParams)
        {
            if (!paramPhaseTargets.TryGetValue(extremeDef.ParamName, out var phaseTargets))
                continue;

            // Skip params where all baselines were already tested
            bool hasNovel = paramReasons.TryGetValue(extremeDef.ParamName, out var reason)
                && !reason.Contains("already tested");

            if (!hasNovel) continue;

            // Clone A: SUPPRESS
            cloneNum++;
            var suppressPlan = BuildSmartExtremePlan(
                cloneNum, sourceSpellName, extremeDef, phaseTargets, isSuppress: true);
            if (suppressPlan != null) batch.Plans.Add(suppressPlan);

            // Clone B: CRANK
            cloneNum++;
            var crankPlan = BuildSmartExtremePlan(
                cloneNum, sourceSpellName, extremeDef, phaseTargets, isSuppress: false);
            if (crankPlan != null) batch.Plans.Add(crankPlan);

            reasonParts.Add($"{extremeDef.ParamName}: {reason}");
        }

        // If nothing novel remains, report it
        if (batch.Plans.Count == 0)
        {
            batch.EmitterReason = "All parameter/emitter combos tested for this spell. Try a different spell type.";
        }
        else
        {
            batch.EmitterReason = $"{batch.Plans.Count} clones ({batch.Plans.Count / 2} novel params). " +
                string.Join("; ", reasonParts.Take(4));
            if (reasonParts.Count > 4)
                batch.EmitterReason += $"; +{reasonParts.Count - 4} more";
        }

        batch.TargetedEmitterIndex = -1; // no single emitter — per-phase targeting
        batch.TotalObservations = batch.Plans.Sum(p => p.PhaseChanges.Count);
        return batch;
    }

    /// <summary>Are two baselines similar enough to skip? Within 10% or both near zero.</summary>
    private static bool IsBaselineSimilar(float tested, float candidate)
    {
        if (Math.Abs(tested) < 0.001f && Math.Abs(candidate) < 0.001f) return true;
        if (Math.Abs(tested) < 0.001f || Math.Abs(candidate) < 0.001f) return false;
        float ratio = candidate / tested;
        return ratio > 0.9f && ratio < 1.1f;
    }

    /// <summary>
    /// How "novel" is this baseline compared to already-tested baselines for the same param+phase?
    /// Higher = more different = more worth testing.
    /// </summary>
    private static float ComputeNovelty(float baseline, string paramName, string phase, List<TestedCombo> tested)
    {
        var relevant = tested.Where(tc => tc.Phase == phase && tc.Parameter == paramName).ToList();
        if (relevant.Count == 0) return 1.0f; // never tested = max novelty

        // Minimum distance from any tested baseline (normalized)
        float minDist = relevant.Min(tc =>
        {
            if (Math.Abs(tc.Baseline) < 0.001f && Math.Abs(baseline) < 0.001f) return 0f;
            if (Math.Abs(tc.Baseline) < 0.001f) return Math.Abs(baseline);
            return Math.Abs(baseline - tc.Baseline) / Math.Max(Math.Abs(tc.Baseline), 0.001f);
        });

        return minDist;
    }

    private ExperimentPlan? BuildSmartExtremePlan(
        int cloneIndex,
        string sourceSpellName,
        ExtremeParamDef extremeDef,
        Dictionary<string, EmitterSnapshot> phaseTargets,
        bool isSuppress)
    {
        var plan = new ExperimentPlan
        {
            CloneIndex = cloneIndex,
            PhaseChanges = new Dictionary<string, ExperimentPhaseChange>()
        };

        string label = isSuppress ? extremeDef.SuppressLabel : extremeDef.CrankLabel;
        var descParts = new List<string>();

        foreach (var (phase, emitter) in phaseTargets)
        {
            float? baseline = extremeDef.ParamName switch
            {
                "scaleStart" => emitter.ScaleStart,
                _ => emitter.TrackValues.GetValueOrDefault(extremeDef.ParamName)
            };

            if (!baseline.HasValue) continue;

            float newValue;
            string mode;

            if (extremeDef.Mode == SweepMode.Multiply)
            {
                float mult = isSuppress ? extremeDef.SuppressMultiplier : extremeDef.CrankMultiplier;
                newValue = baseline.Value * mult;
                mode = $"×{mult}";
            }
            else
            {
                newValue = isSuppress ? extremeDef.SuppressAbsolute : extremeDef.CrankAbsolute;
                mode = $"={newValue}";
            }

            if (Math.Abs(newValue - baseline.Value) < 0.001f) continue;
            newValue = MathF.Round(newValue, 3);

            plan.PhaseChanges[phase] = new ExperimentPhaseChange
            {
                Phase = phase,
                EmitterIndex = emitter.Index,
                Parameter = extremeDef.ParamName,
                BaselineValue = baseline.Value,
                NewValue = newValue,
                Mode = mode,
                ParameterDescription = extremeDef.Description,
            };

            descParts.Add($"{phase}/em{emitter.Index}: {extremeDef.ParamName} {baseline.Value:F2}→{newValue:F2}");
        }

        if (descParts.Count == 0) return null;

        plan.SpellName = $"{sourceSpellName} X{cloneIndex:D2}";
        plan.SpellDescription = $"[EXTREME #{cloneIndex} {label}] {string.Join(" | ", descParts)}";

        return plan;
    }

    /// <summary>
    /// Record observations from an experiment batch.
    /// Takes the clone index and observation notes, merges them into
    /// the archetype knowledge base.
    ///
    /// This is the "quantize" step — raw observations become archetype
    /// refinements and parameter significance notes.
    /// </summary>
    public void RecordObservation(ExperimentObservation observation)
    {
        // Load or create the experiment log
        string logPath = Path.Combine(BasePath, "experiment_log.json");
        var log = new List<ExperimentObservation>();

        if (File.Exists(logPath))
        {
            try
            {
                log = JsonSerializer.Deserialize<List<ExperimentObservation>>(
                    File.ReadAllText(logPath), _jsonOpts) ?? new();
            }
            catch { /* start fresh */ }
        }

        observation.RecordedAt = DateTime.UtcNow;
        log.Add(observation);

        File.WriteAllText(logPath, JsonSerializer.Serialize(log, _jsonOpts));
        _logger.LogInformation("SpellDNA: Recorded observation for {Spell} clone #{Clone}",
            observation.SourceSpellName, observation.CloneIndex);
    }

    /// <summary>Get all recorded observations.</summary>
    public List<ExperimentObservation> GetObservations()
    {
        string logPath = Path.Combine(BasePath, "experiment_log.json");
        if (!File.Exists(logPath)) return new();

        try
        {
            return JsonSerializer.Deserialize<List<ExperimentObservation>>(
                File.ReadAllText(logPath), _jsonOpts) ?? new();
        }
        catch { return new(); }
    }



    private void PersistArchetypes()
    {
        var list = _archetypes.Values.ToList();
        File.WriteAllText(ArchetypesPath, JsonSerializer.Serialize(list, _jsonOpts));
    }

    private static string SanitizeFilename(string name)
    {
        var invalid = Path.GetInvalidFileNameChars();
        return new string(name.Select(c => invalid.Contains(c) ? '_' : c).ToArray())
            .Replace(' ', '_');
    }

    private static readonly JsonSerializerOptions _jsonOpts = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase) }
    };
}


// ═══════════════════════════════════════════════════════════════════════
//  TIER 1 DATA MODEL: EMITTER ARCHETYPES
// ═══════════════════════════════════════════════════════════════════════

/// <summary>
/// A named emitter behavior pattern.
///
/// An archetype captures: "when you see these parameter ranges together,
/// the visual result is [X], and here's why each parameter matters."
///
/// Archetypes are the vocabulary of spell visual design. Instead of
/// thinking in raw numbers (rate=40, life=0.7, speed=0.194), you think
/// in behavior names: "upward_drift", "fast_scatter", "imploding_gather".
/// </summary>
public class EmitterArchetype
{
    /// <summary>Machine-readable ID, e.g. "upward_drift", "fast_scatter".</summary>
    public string Id { get; set; } = "";

    /// <summary>Human-readable name, e.g. "Upward Drift".</summary>
    public string Name { get; set; } = "";

    /// <summary>
    /// Detailed explanation of what this behavior looks like and why
    /// the parameter combination produces it. This is the knowledge.
    /// </summary>
    public string Description { get; set; } = "";

    /// <summary>One-line description of the visible result.</summary>
    public string VisualResult { get; set; } = "";

    /// <summary>Known vanilla spells that exhibit this behavior.</summary>
    public List<string> ExampleSpells { get; set; } = new();

    /// <summary>
    /// The parameter fingerprint that defines this archetype.
    /// Each entry specifies a parameter name, acceptable range (min/max),
    /// and a human-readable explanation of why this range matters.
    /// </summary>
    public List<ParamFingerprint> Fingerprint { get; set; } = new();

    /// <summary>
    /// If set, only emitters of this type can match this archetype.
    /// 0=point, 1=sphere, 2=plane, 3=spline. Null = any type.
    /// </summary>
    public byte? RequiredEmitterType { get; set; }

    /// <summary>When this archetype was last updated.</summary>
    public DateTime? LastUpdated { get; set; }
}

/// <summary>
/// One parameter range in an archetype's fingerprint.
/// Captures not just the range, but WHY this range matters
/// for producing the archetype's visual behavior.
/// </summary>
public class ParamFingerprint
{
    /// <summary>
    /// Parameter name — matches M2EmitterParser property names:
    /// "emissionRate", "lifespan", "emissionSpeed", "gravity",
    /// "emissionAreaLength", "emissionAreaWidth", "verticalRange",
    /// "horizontalRange", "speedVariation", "scaleStart", "scaleMid",
    /// "scaleEnd", "blendMode"
    /// </summary>
    public string Parameter { get; set; } = "";

    /// <summary>Minimum value for this parameter in this archetype.</summary>
    public float Min { get; set; }

    /// <summary>Maximum value for this parameter in this archetype.</summary>
    public float Max { get; set; }

    /// <summary>
    /// Why does this parameter value matter for this archetype?
    /// e.g. "Low speed = particles barely move on their own, so gravity dominates"
    /// This is the knowledge capture field.
    /// </summary>
    public string? Significance { get; set; }
}

/// <summary>Result of classifying an emitter against archetypes.</summary>
public class ArchetypeMatch
{
    public string ArchetypeId { get; set; } = "";
    public string ArchetypeName { get; set; } = "";

    /// <summary>Match score 0-1. Above 0.3 = plausible, above 0.7 = strong match.</summary>
    public float Score { get; set; }
}


// ═══════════════════════════════════════════════════════════════════════
//  TIER 2 DATA MODEL: M2 PROFILES
// ═══════════════════════════════════════════════════════════════════════

/// <summary>
/// Complete structural profile of a single M2 file.
/// Documents what the M2 contains (emitters, textures, wiring)
/// and classifies each emitter against known archetypes.
///
/// This answers: "What does this M2 file DO, compositionally?"
/// </summary>
public class M2Profile
{
    /// <summary>M2 filename (no path), e.g. "Fire_Precast_Hand.m2".</summary>
    public string M2Filename { get; set; } = "";

    /// <summary>Relative path from client M2 root, e.g. "Spells/Fire_Precast_Hand.m2".</summary>
    public string M2Path { get; set; } = "";

    /// <summary>When this profile was last scanned/updated.</summary>
    public DateTime ScannedAt { get; set; }

    /// <summary>Total emitter count.</summary>
    public int EmitterCount { get; set; }

    /// <summary>Total texture count.</summary>
    public int TextureCount { get; set; }

    /// <summary>
    /// Human-written summary of what this M2 does compositionally.
    /// e.g. "5-emitter precast: upward sparks + imploding gather + glow pulse.
    ///       Creates a hand-held charging fireball effect."
    /// Null until manually annotated.
    /// </summary>
    public string? Summary { get; set; }

    /// <summary>
    /// Which vanilla spells use this M2 (for reference).
    /// e.g. ["Fireball precast", "Fire Blast precast"]
    /// </summary>
    public List<string>? UsedBySpells { get; set; }

    /// <summary>Per-emitter profile data.</summary>
    public List<ProfileEmitter> Emitters { get; set; } = new();

    /// <summary>Per-texture profile data.</summary>
    public List<ProfileTexture> Textures { get; set; } = new();
}

/// <summary>
/// Profile data for a single emitter within an M2.
/// Stores raw parameter values + archetype classification.
/// </summary>
public class ProfileEmitter
{
    public int Index { get; set; }
    public ushort TextureId { get; set; }
    public byte BlendMode { get; set; }
    public byte EmitterType { get; set; }

    // Raw M2Track values
    public float? EmissionRate { get; set; }
    public float? Lifespan { get; set; }
    public float? EmissionSpeed { get; set; }
    public float? Gravity { get; set; }
    public float? EmissionAreaLength { get; set; }
    public float? EmissionAreaWidth { get; set; }
    public float? VerticalRange { get; set; }
    public float? HorizontalRange { get; set; }
    public float? SpeedVariation { get; set; }
    public float ScaleStart { get; set; }
    public float ScaleMid { get; set; }
    public float ScaleEnd { get; set; }

    // Classification
    /// <summary>Best-matching archetype ID, or null if unclassified.</summary>
    public string? ArchetypeId { get; set; }

    /// <summary>Classification confidence (0-1).</summary>
    public float? ArchetypeScore { get; set; }

    /// <summary>
    /// Human-written description of what this specific emitter does
    /// in the context of this M2's composition.
    /// e.g. "Rising orange sparks from the palm — sells 'charging fire' feel"
    /// Null until manually annotated.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Human description of the emitter+texture combination effect.
    /// e.g. "Glow texture on upward_drift = soft rising light wisps"
    /// </summary>
    public string? CombinationEffect { get; set; }
}

/// <summary>
/// Profile data for a single texture within an M2.
/// </summary>
public class ProfileTexture
{
    public int Index { get; set; }
    public string VanillaFilename { get; set; } = "";

    /// <summary>Texture role from recipe or manual annotation.</summary>
    public string? Role { get; set; }

    /// <summary>Texture job from recipe.</summary>
    public string? Job { get; set; }

    /// <summary>Density classification.</summary>
    public string? Density { get; set; }

    /// <summary>
    /// What this texture looks like and why it matters.
    /// e.g. "Dense molten rock pattern — used as the solid core of the fireball.
    ///       FullCoverage means the entire particle sprite is filled with content."
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Which emitter indices reference this texture.
    /// Computed from M2 data during profiling.
    /// </summary>
    public List<int>? ReferencedByEmitters { get; set; }
}


// ═══════════════════════════════════════════════════════════════════════
//  TIER 3 DATA MODEL: SPELL DNA
// ═══════════════════════════════════════════════════════════════════════

/// <summary>
/// The intent document for a custom spell.
///
/// Maps human creative vision to concrete M2+texture+emitter configuration.
/// Every parameter has an optional "why" annotation — this is how knowledge
/// accumulates. When we tune a value and observe the result in-game, we
/// write down WHY that value works.
///
/// A SpellDna can be COMPILED into a SpellTuningPreset for execution.
/// The DNA is the design spec; the preset is the build artifact.
/// </summary>
public class SpellDna
{
    /// <summary>Spell name, matching the custom spell name.</summary>
    public string SpellName { get; set; } = "";

    /// <summary>Source spell entry ID.</summary>
    public int SourceSpellEntry { get; set; }

    /// <summary>Visual theme keyword (lightning, fire, shadow, frost, holy, etc.).</summary>
    public string? Theme { get; set; }

    /// <summary>
    /// High-level creative intent — what the spell should look and feel like.
    /// e.g. "Naruto-style Chidori: bright white-blue lightning concentrated in hand,
    ///       electric arcs escaping rapidly, crackling energy sound"
    /// </summary>
    public string? Intent { get; set; }

    /// <summary>Per-phase visual design.</summary>
    public Dictionary<string, DnaPhase> Phases { get; set; } = new();

    /// <summary>Document version — incremented on each save.</summary>
    public int Version { get; set; } = 1;

    /// <summary>When this DNA was created.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>When this DNA was last modified.</summary>
    public DateTime? ModifiedAt { get; set; }

    /// <summary>
    /// Session notes — what we learned from testing this spell.
    /// Append-only log of observations.
    /// </summary>
    public List<string>? ObservationLog { get; set; }
}

/// <summary>
/// One phase of a spell's visual DNA.
/// Contains the M2 source and the list of visual elements (emitter+texture pairs).
/// </summary>
public class DnaPhase
{
    /// <summary>M2 file path for this phase.</summary>
    public string? SourceM2 { get; set; }

    /// <summary>
    /// What this phase should look like overall.
    /// e.g. "Lightning gathering in palm, crackling intensity building over 1.5 seconds"
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// The visual elements that compose this phase.
    /// Each element = one emitter + its texture + the behavior archetype.
    /// </summary>
    public List<SpellElement> Elements { get; set; } = new();
}

/// <summary>
/// One visual element within a spell phase.
///
/// A SpellElement represents the combination of:
///   emitter behavior (archetype + specific param values) +
///   texture appearance (role + source image)
///   = a named visual component of the spell
///
/// This is the fundamental unit of spell visual composition.
/// "Fireball has 5 elements in its precast: rising sparks, imploding gather,
///  left glow, right glow, wide gather."
/// </summary>
public class SpellElement
{
    /// <summary>
    /// Human-readable name for this element.
    /// e.g. "core_ball", "escaping_arcs", "ambient_glow"
    /// </summary>
    public string Name { get; set; } = "";

    /// <summary>
    /// What this element should look like.
    /// e.g. "Tight flickering bright ball in hand"
    /// </summary>
    public string? VisualGoal { get; set; }

    /// <summary>Which archetype this element uses.</summary>
    public string? ArchetypeId { get; set; }

    /// <summary>Which emitter index in the M2 this element maps to.</summary>
    public int EmitterIndex { get; set; }

    /// <summary>
    /// Parameter values with "why" annotations.
    /// Keys match M2EmitterParser property names.
    /// Each value carries both the number and the reasoning.
    /// </summary>
    public Dictionary<string, AnnotatedValue>? Params { get; set; }

    /// <summary>Texture assignment for this element.</summary>
    public ElementTexture? Texture { get; set; }
}

/// <summary>
/// A parameter value with an explanation of why it's set to that value.
/// The "why" is the knowledge capture mechanism — it accumulates
/// understanding across tuning iterations.
/// </summary>
public class AnnotatedValue
{
    /// <summary>The numeric value.</summary>
    public float Value { get; set; }

    /// <summary>
    /// Why this value? What does it produce visually?
    /// e.g. "80 particles/sec = dense enough to look solid at scale 0.25"
    /// Null until we observe and annotate.
    /// </summary>
    public string? Why { get; set; }

    /// <summary>
    /// What was the previous value before this change?
    /// Helps track the tuning journey.
    /// </summary>
    public float? PreviousValue { get; set; }
}

/// <summary>
/// Texture specification within a SpellElement.
/// Defines what texture this emitter should use and why.
/// </summary>
public class ElementTexture
{
    /// <summary>Texture index in the M2's texture table.</summary>
    public int TextureIndex { get; set; }

    /// <summary>Texture role: Body, Glow, Shape, Ring, Atlas, Ribbon, Bloom.</summary>
    public string? Role { get; set; }

    /// <summary>Texture job: Core, Trail, Mass, Streak, etc.</summary>
    public string? Job { get; set; }

    /// <summary>Density: FullCoverage or CenteredShape.</summary>
    public string? Density { get; set; }

    /// <summary>Original vanilla filename this slot had.</summary>
    public string? VanillaFilename { get; set; }

    /// <summary>
    /// Source PNG for generation/reprocessing.
    /// Filled in when we assign a custom texture.
    /// </summary>
    public string? SourcePng { get; set; }

    /// <summary>Brightness floor override.</summary>
    public float? FloorPercent { get; set; }

    /// <summary>Knee width override.</summary>
    public float? KneeWidth { get; set; }

    /// <summary>
    /// Why this texture was chosen for this element.
    /// e.g. "FullCoverage body texture because the dense_flicker archetype
    ///       overlaps many particles — transparent sprites would look washed out"
    /// </summary>
    public string? Why { get; set; }
}


// ═══════════════════════════════════════════════════════════════════════
//  EXPERIMENT ENGINE DATA MODEL
// ═══════════════════════════════════════════════════════════════════════

/// <summary>How test values are computed from baseline.</summary>
public enum SweepMode
{
    /// <summary>Test value = baseline × multiplier. For rate, life, scale, area.</summary>
    Multiply,
    /// <summary>Test value = absolute replacement. For speed, gravity (where sign matters).</summary>
    Absolute
}

/// <summary>Definition of one sweepable parameter.</summary>
public class SweepParamDef
{
    public string ParamName { get; }
    public SweepMode Mode { get; }
    public float[] TestValues { get; }
    public string Description { get; }

    public SweepParamDef(string paramName, SweepMode mode, float[] testValues, string description)
    {
        ParamName = paramName;
        Mode = mode;
        TestValues = testValues;
        Description = description;
    }
}

/// <summary>
/// Definition of one extreme-sweep parameter.
/// Two values per param: suppress (near-zero) and crank (max).
/// </summary>
public class ExtremeParamDef
{
    public string ParamName { get; }
    public SweepMode Mode { get; }
    public float SuppressMultiplier { get; }
    public float CrankMultiplier { get; }
    public float SuppressAbsolute { get; }
    public float CrankAbsolute { get; }
    public string SuppressLabel { get; }
    public string CrankLabel { get; }
    public string Description { get; }

    public ExtremeParamDef(string paramName, SweepMode mode,
        float suppressMultiplier = 0, float crankMultiplier = 0,
        float suppressAbsolute = 0, float crankAbsolute = 0,
        string suppressLabel = "SUPPRESS", string crankLabel = "CRANK",
        string description = "")
    {
        ParamName = paramName;
        Mode = mode;
        SuppressMultiplier = suppressMultiplier;
        CrankMultiplier = crankMultiplier;
        SuppressAbsolute = suppressAbsolute;
        CrankAbsolute = crankAbsolute;
        SuppressLabel = suppressLabel;
        CrankLabel = crankLabel;
        Description = description;
    }
}

/// <summary>
/// A complete experiment batch — the plan for N spell clones
/// that systematically explore the parameter space of a source spell.
/// </summary>
public class ExperimentBatch
{
    public int SourceSpellEntry { get; set; }
    public string SourceSpellName { get; set; } = "";
    public DateTime CreatedAt { get; set; }

    /// <summary>Total observations across all clones (sum of phase changes).</summary>
    public int TotalObservations { get; set; }

    /// <summary>Which emitter index this batch targets.</summary>
    public int TargetedEmitterIndex { get; set; }

    /// <summary>Why this emitter was selected (auto-advance reason).</summary>
    public string? EmitterReason { get; set; }

    /// <summary>The individual clone plans.</summary>
    public List<ExperimentPlan> Plans { get; set; } = new();
}

/// <summary>
/// Plan for a single experiment clone.
/// One change per phase, description carries the full changelog.
/// </summary>
public class ExperimentPlan
{
    /// <summary>1-based index within the batch.</summary>
    public int CloneIndex { get; set; }

    /// <summary>Name for the clone, e.g. "Fireball E03".</summary>
    public string SpellName { get; set; } = "";

    /// <summary>
    /// Goes into spell_template.description — visible in client tooltip.
    /// e.g. "[EXP #3] precast/em0: rate 40→80 | missile/em1: life 0.7→0.3"
    /// </summary>
    public string SpellDescription { get; set; } = "";

    /// <summary>One change per phase.</summary>
    public Dictionary<string, ExperimentPhaseChange> PhaseChanges { get; set; } = new();
}

/// <summary>
/// What changes in one phase of one experiment clone.
/// </summary>
public class ExperimentPhaseChange
{
    public string Phase { get; set; } = "";
    public int EmitterIndex { get; set; }
    public string Parameter { get; set; } = "";
    public float BaselineValue { get; set; }
    public float NewValue { get; set; }

    /// <summary>Human-readable change mode, e.g. "×2.0" or "=5.0".</summary>
    public string Mode { get; set; } = "";

    /// <summary>What this parameter controls.</summary>
    public string ParameterDescription { get; set; } = "";

    // ── Observation fields (filled after in-game testing) ──

    /// <summary>What did you see? Free-form notes.</summary>
    public string? Observation { get; set; }

    /// <summary>
    /// Impact rating: 0=no visible change, 1=subtle, 2=noticeable, 3=dramatic.
    /// </summary>
    public int? ImpactRating { get; set; }
}

/// <summary>
/// Post-experiment observation record.
/// The user reports what they saw for one clone after in-game testing.
/// </summary>
public class ExperimentObservation
{
    public int SourceSpellEntry { get; set; }
    public string SourceSpellName { get; set; } = "";
    public int CloneIndex { get; set; }
    public int CloneSpellEntry { get; set; }

    /// <summary>Per-phase observations.</summary>
    public Dictionary<string, PhaseObservation> Phases { get; set; } = new();

    /// <summary>Overall impression of this clone.</summary>
    public string? OverallNotes { get; set; }

    public DateTime RecordedAt { get; set; }
}

/// <summary>Observation for one phase of one experiment clone.</summary>
public class PhaseObservation
{
    public string Parameter { get; set; } = "";
    public float BaselineValue { get; set; }
    public float NewValue { get; set; }
    public string? Observation { get; set; }

    /// <summary>0=invisible, 1=subtle, 2=noticeable, 3=dramatic</summary>
    public int ImpactRating { get; set; }
}


// ═══════════════════════════════════════════════════════════════════════
//  EXPERIMENT SUMMARY — Accumulated knowledge per spell
// ═══════════════════════════════════════════════════════════════════════

/// <summary>
/// Accumulated experiment knowledge for one spell.
/// Tracks which emitters/parameters have been tested and what was learned.
/// Used by PlanExtremeExperiments to auto-advance to untested emitters.
/// Stored at /opt/mangossuperui/spelldna/summaries/{SpellName}.json
/// </summary>
public class ExperimentSummary
{
    public string SpellName { get; set; } = "";
    public int SourceEntry { get; set; }

    /// <summary>Completed experiment batches with findings.</summary>
    public List<BatchSummary> Batches { get; set; } = new();

    /// <summary>Emitter indices not yet tested.</summary>
    public List<int> EmittersRemaining { get; set; } = new();

    /// <summary>Suggestion for what to test next.</summary>
    public string? NextBatchSuggestion { get; set; }
}

/// <summary>Summary of one completed experiment batch.</summary>
public class BatchSummary
{
    public int BatchId { get; set; }
    public string Mode { get; set; } = "extreme";
    public string Date { get; set; } = "";

    /// <summary>Which emitter index was targeted in this batch (legacy — use TestedCombos for per-phase).</summary>
    public int EmitterTargeted { get; set; }

    /// <summary>Why this emitter was selected.</summary>
    public string? EmitterSelectionReason { get; set; }

    /// <summary>Which phases had emitters to test.</summary>
    public List<string> PhasesFound { get; set; } = new();

    /// <summary>Which parameters were covered in this batch.</summary>
    public List<string> ParametersCovered { get; set; } = new();

    /// <summary>
    /// Per-phase, per-emitter, per-parameter combos tested in this batch.
    /// Used to skip redundant tests in future batches.
    /// </summary>
    public List<TestedCombo>? TestedCombos { get; set; }

    /// <summary>Synthesized findings from this batch.</summary>
    public BatchFindings? Findings { get; set; }
}

/// <summary>
/// Records one tested (phase, emitter, parameter, baseline) combination.
/// Two combos with the same parameter and similar baselines (within 10%)
/// are considered equivalent — no need to re-test.
/// </summary>
public class TestedCombo
{
    public string Phase { get; set; } = "";
    public int EmitterIndex { get; set; }
    public string Parameter { get; set; } = "";
    public float Baseline { get; set; }
}

/// <summary>Synthesized findings from one experiment batch.</summary>
public class BatchFindings
{
    /// <summary>Parameters ranked from most to least visual impact.</summary>
    public List<string> ParameterRanking { get; set; } = new();

    /// <summary>Per-parameter findings.</summary>
    public Dictionary<string, ParameterFinding> PerParameter { get; set; } = new();
}

/// <summary>What we learned about one parameter from an experiment batch.</summary>
public class ParameterFinding
{
    public float SuppressValue { get; set; }
    public float CrankValue { get; set; }
    public string SuppressImpact { get; set; } = "";
    public string CrankImpact { get; set; } = "";
    public string? Notes { get; set; }
}